// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kLBHGn3Vn82YBnTDGnqJfk
// Component: JUJxh7K9DX

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: kLBHGn3Vn82YBnTDGnqJfk/projectcss
import sty from "./PlasmicHeaderText.module.css"; // plasmic-import: JUJxh7K9DX/css

export type PlasmicHeaderText__VariantMembers = {
  color: "white";
};
export type PlasmicHeaderText__VariantsArgs = {
  color?: SingleChoiceArg<"white">;
};
type VariantPropType = keyof PlasmicHeaderText__VariantsArgs;
export const PlasmicHeaderText__VariantProps = new Array<VariantPropType>(
  "color"
);

export type PlasmicHeaderText__ArgsType = {
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicHeaderText__ArgsType;
export const PlasmicHeaderText__ArgProps = new Array<ArgPropType>("children");

export type PlasmicHeaderText__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultHeaderTextProps {
  children?: React.ReactNode;
  color?: SingleChoiceArg<"white">;
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHeaderText__RenderFunc(props: {
  variants: PlasmicHeaderText__VariantsArgs;
  args: PlasmicHeaderText__ArgsType;
  overrides: PlasmicHeaderText__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "color",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.color
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, { $props, $ctx, $queries });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root,
        { [sty.rootcolor_white]: hasVariant($state, "color", "white") }
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: "133462",
        value: args.children,
        className: classNames(sty.slotTargetChildren, {
          [sty.slotTargetChildrencolor_white]: hasVariant(
            $state,
            "color",
            "white"
          )
        })
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeaderText__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeaderText__VariantsArgs;
    args?: PlasmicHeaderText__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeaderText__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHeaderText__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHeaderText__ArgProps,
          internalVariantPropNames: PlasmicHeaderText__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeaderText__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeaderText";
  } else {
    func.displayName = `PlasmicHeaderText.${nodeName}`;
  }
  return func;
}

export const PlasmicHeaderText = Object.assign(
  // Top-level PlasmicHeaderText renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHeaderText
    internalVariantProps: PlasmicHeaderText__VariantProps,
    internalArgProps: PlasmicHeaderText__ArgProps
  }
);

export default PlasmicHeaderText;
/* prettier-ignore-end */
