// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kLBHGn3Vn82YBnTDGnqJfk
// Component: sSdXxYFyEs

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: FxpPQ7-wWLy/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic_antd_5_hostless.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: kLBHGn3Vn82YBnTDGnqJfk/projectcss
import sty from "./PlasmicNavSubMenu.module.css"; // plasmic-import: sSdXxYFyEs/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: nuudgiLMynC/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: logztJZIqxF/icon

export type PlasmicNavSubMenu__VariantMembers = {};
export type PlasmicNavSubMenu__VariantsArgs = {};
type VariantPropType = keyof PlasmicNavSubMenu__VariantsArgs;
export const PlasmicNavSubMenu__VariantProps = new Array<VariantPropType>();

export type PlasmicNavSubMenu__ArgsType = {};
type ArgPropType = keyof PlasmicNavSubMenu__ArgsType;
export const PlasmicNavSubMenu__ArgProps = new Array<ArgPropType>();

export type PlasmicNavSubMenu__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultNavSubMenuProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicNavSubMenu__RenderFunc(props: {
  variants: PlasmicNavSubMenu__VariantsArgs;
  args: PlasmicNavSubMenu__ArgsType;
  overrides: PlasmicNavSubMenu__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          projectcss.plasmic_tokens,
          plasmic_antd_5_hostless_css.plasmic_tokens,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <Button className={classNames("__wab_instance", sty.button__tVx3T)} />

          <Button className={classNames("__wab_instance", sty.button__dUvS)} />

          <Button className={classNames("__wab_instance", sty.button__pwbzj)} />

          <Button
            className={classNames("__wab_instance", sty.button___8HNHj)}
          />
        </div>
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavSubMenu__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavSubMenu__VariantsArgs;
    args?: PlasmicNavSubMenu__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavSubMenu__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNavSubMenu__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicNavSubMenu__ArgProps,
          internalVariantPropNames: PlasmicNavSubMenu__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavSubMenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavSubMenu";
  } else {
    func.displayName = `PlasmicNavSubMenu.${nodeName}`;
  }
  return func;
}

export const PlasmicNavSubMenu = Object.assign(
  // Top-level PlasmicNavSubMenu renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicNavSubMenu
    internalVariantProps: PlasmicNavSubMenu__VariantProps,
    internalArgProps: PlasmicNavSubMenu__ArgProps
  }
);

export default PlasmicNavSubMenu;
/* prettier-ignore-end */
